name: TikTok Bot 24/7

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Bot
      env:
        API_ID: ${{ secrets.API_ID }}
        API_HASH: ${{ secrets.API_HASH }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        GROUP_ID: ${{ secrets.GROUP_ID }}
        CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
      run: python main.py
